FROM maven:3.9.9-sapmachine-21 AS build
RUN mkdir -p /workspace
WORKDIR /workspace
COPY pom.xml /workspace
COPY src /workspace/src
COPY selfsigned.crt /workspace
RUN mvn -B package --file pom.xml -DskipTests

FROM openjdk:21-slim
COPY --from=build /workspace/selfsigned.crt selfsigned.crt
RUN keytool -importcert -keypass changeit -file selfsigned.crt -keystore ${JAVA_HOME}/lib/security/cacerts -noprompt -storepass changeit -alias 83.166.236.78
COPY --from=build /workspace/target/jpixelscoringbot*.jar jpixelscoringbot.jar
ENTRYPOINT exec java -jar jpixelscoringbot.jar