spring:
  liquibase:
    change-log: db/changeset-master.xml
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

settings:
  adminNicknames: ${settings.adminNicknames}
  lifeTimeReportInMonths: ${settings.lifeTimeReportInMonths}
  numberOfQuestionsAboutJava: ${settings.numberOfQuestionsAboutJava}

minio:
  host: ${minio.host}
  accessToken: ${minio.accessToken}
  secretToken: ${minio.secretToken}
  nameBucket: ${minio.nameBucket}

telegram:
  bot:
    token: ${telegram_bot_token}
    username: ${telegram_bot_username}